### ISSUE TITLE
Would it be possible to update the Docker on DockerHub?

### ISSUE THREAD

**Issue by tonyreina** [boutroslab/cld_docker#14]
https://hub.docker.com/r/boutroslab/cld_docker

Could this Docker image be updated with the latest version of the code? I wanted to get the progress bar going and it's easier to run things via the Docker.

Thanks!

**Comment by tonyreina** [comment]
I pushed my own build here:  https://hub.docker.com/repository/docker/tbreina1/cld-crispr-designer

It's just the latest build from this repository.

**Comment by fheigwer** [comment]
Hi Tony,

I’ll see that I push this once there is a time window in my schedule.

Thanks for the contributions.

Best,
Florian

--
Prof. Dr. Florian Heigwer
Signaling and Functional Genomics/B110
Scientist

German Cancer Research Center (DKFZ)
Foundation under Public Law
Im Neuenheimer Feld 580
69120 Heidelberg
Germany



Von: Tony Reina ***@***.***>
Antworten an: boutroslab/cld_docker ***@***.***>
Datum: Freitag, 6. Januar 2023 um 00:10
An: boutroslab/cld_docker ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [boutroslab/cld_docker] Would it be possible to update the Docker on DockerHub? (Issue #14)


I pushed my own build here: https://hub.docker.com/repository/docker/tbreina1/cld-crispr-designer

It's just the latest build from this repository.
